name: Build and deploy

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Ivy Cache
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{runner.os}}-sbt-${{hashFiles('**/build.sbt')}}
      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{runner.os}}-sbt-${{hashFiles('**/build.sbt')}}
      - name: Coursier cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: ${{ runner.os }}-coursier-cache-${{ matrix.scala }}-${{ hashFiles('**/*.sbt') }}
          restore-keys: |
            ${{ runner.os }}-coursier-cache-${{ matrix.scala }}-${{ hashFiles('**/*.sbt') }}-
            ${{ runner.os }}-coursier-cache-${{ matrix.scala }}-
            ${{ runner.os }}-coursier-cache-
      - name: Build packages
        run: sbt assembly
      - name: Bundle functions
        run: tar -cvf functions.tar domain-setup/target/scala-2.13/deploy/domain-setup-function.jar
      - name: Save function jars
        uses: actions/upload-artifact@v2
        with:
          name: all-functions
          retention-days: 1
          path: functions.tar

  deploy-domain-setup:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve compiled functions
        uses: actions/download-artifact@v2
        with:
          name: all-functions
      - name: Unpack functions
        run: tar -xvf functions.tar
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.TEST_PROJECT_ID }}
          service_account_key: ${{ secrets.TEST_SA_KEY }}
          export_default_credentials: true
      - name: Test GCloud config
        run: gcloud info
      - name: Deploy domain-setup
        working-directory: ./domain-setup/target/scala-2.13/deploy
        run: >-
          gcloud functions deploy domain-setup
          --entry-point it.ldsoftware.webfleet.functions.CreateDomainStructure
          --runtime java11
          --trigger-event providers/cloud.firestore/eventTypes/document.create
          --trigger-resource projects/${{ secrets.TEST_PROJECT_ID }}/databases/\(default\)/documents/domains/{domainId}
          --region europe-west1
